# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: roxygenize
        # roxygen requires loading pkg -> add dependencies from DESCRIPTION
        additional_dependencies:
        -   shiny
        -   shinydashboard
        -   shinyWidgets
        -   shinyjs
        -   config
        -   golem
        -   lifecycle
        -   precommit
        -   docopt
        -   magrittr
        -   dplyr
        -   tidyr
        -   hrbrmstr/xattrs
        -   checkmate
        -   rlang
        -   glue
        -   purrr
        -   reactable
        -   reactable.extras
        -   bslib
        -   htmltools
        -   grDevices
        -   shinyFeedback
        -   shinyalert
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.feather|
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.sh|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)\.travis\.yml|
          (.*/|)appveyor\.yml|
          (.*/|)NAMESPACE|
          (.*/|)renv/settings\.dcf|
          (.*/|)renv\.lock|
          (.*/|)renv/activate\.R|
          (.*/|)WORDLIST|
          \.github/workflows/.*|
          data/.*|
          (.*/|)dev/.*|
          (.*/|)docker/.*|
          (.*/|)inst/app/.*|
          (.*/|)inst/assets/.*|
          (.*/|)inst/demos/.*|
          (.*/|)tests/testthat/sbgenomics_test/.*|
          )$
    -   id: lintr
        exclude: >
              (?x)^(
              (.*/|)dev/.*|
              (.*/|)inst/app/.*|
              (.*/|)inst/assets/.*|
              (.*/|)docker/.*|
              (.*/|)renv/activate\.R|
              )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-print-statement
        exclude: >
              (?x)^(
              (.*/|)renv/activate\.R|
              (.*/|)R/mod_save_plot_to_export-utils\.R|
              )$
    -   id: no-debug-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: file-contents-sorter
        files: '^\.Rbuildignore$'
    -   id: end-of-file-fixer
        exclude: '\.Rd|\.md'
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files

ci:
    autoupdate_schedule: monthly
