#' Define file picker's modal dialog UI.
#'
#' @description
#'  This utility function creates the UI for the file picker's modal dialog.
#'  It is designed to be used within the server function of the Shiny module
#'  to keep the server code clean and maintainable by extracting the modal UI
#'  components into a separate function.
#'
#' @param ns A namespace function generated by \code{\link[shiny]{NS}} in the
#'  file picker's module.
#' @param selection_type A string specifying the selection mode. Can be either
#'  `single` for single file selection or `multiple` for multiple file
#'   selection. Defaults to `single`.
#'
#' @return A Shiny modal dialog UI object.
#'
#' @importFrom shinyWidgets useShinydashboard
#' @importFrom shinydashboard box
#' @importFrom reactable.extras reactable_extras_dependency
#' @importFrom reactable reactableOutput
#' @importFrom bslib input_task_button
#'
#' @noRd
file_picker_modal_ui <- function(ns, selection_type) {
  # nolint start
  modalDialog(
    title = "File Selection",
    size = "l",
    shinyWidgets::useShinydashboard(),
    fluidRow(
      div(
        shinydashboard::box(
          title = "File Selection Guides",
          width = 12,
          collapsible = TRUE,
          collapsed = TRUE,
          tags$div(
            tags$p("To efficiently manage files, follow these steps:"),
            tags$ol(
              tags$li("Review file details."),
              if (selection_type == "single") {
                tags$li(HTML("To select a file, click the radio button in the leftmost column of the desired file's row."))
              } else {
                tags$li(HTML("Use the checkboxes in each row to select multiple files simultaneously."))
              },
              tags$li(HTML("Use the search bar above the table to quickly locate a file by its name or metadata.")),
              tags$li(HTML("Utilize the filter options to narrow down the file list based on specific criteria.")),
              tags$li(HTML("Click on column headers to sort files in ascending or descending order.")),
              tags$li(HTML("Use pagination controls at the bottom of the table to navigate through multiple pages of files.")),
              tags$li(HTML("Once you're ready with your choice, click <b>Submit</b> located below the table."))
            )
          )
        )
      )
    ),
    # nolint end
    fluidRow(
      div(
        class = "file-selection-table",
        shinydashboard::box(
          title = "Files Table Preview",
          width = 12,
          collapsible = FALSE,
          tags$div(
            id = ns("file_picker_selection"),
            reactable.extras::reactable_extras_dependency(),
            reactable::reactableOutput(ns("table"))
          ),
          br(),
          h5("Selected file"),
          verbatimTextOutput(ns("selected_files"),
            placeholder = TRUE
          ),
          br()
        )
      )
    ),
    footer = tagList(
      actionButton(ns("dismiss"),
        label = "Dismiss",
        icon = icon("xmark")
      ),
      bslib::input_task_button(
        id = ns("submit_selection"),
        label = "Submit",
        icon = icon("check"),
        type = "default"
      )
    )
  )
}
